### ISSUE TITLE
Investigate flaky test case on macOS

### ISSUE THREAD

**Issue by andreaswilli** [andreaswilli/meta-grabber#34]
Test case `change ui language` failed on macOS, worked on the second run though.

```
FAIL tests/app.test.js ([9](https://github.com/andreaswilli/meta-grabber/runs/5168925566?check_suite_focus=true#step:5:9).016 s)
  Home
    ✓ show initial instructions in snackbar (14 ms)
  Settings
    ✕ change ui language (668 ms)

  ● Settings › change ui language

    expect(received).toBe(expected) // Object.is equality

    Expected: "Einstellungen"
    Received: "Settings"

      53 | async function expectText(selector, expectedText) {
      54 |   const actualText = await page.$eval(selector, (el) => el.innerText)
    > 55 |   expect(actualText).toBe(expectedText)
         |                      ^
      56 | }
      57 |

      at _callee6$ (tests/app.test.js:55:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at asyncGeneratorStep (tests/app.test.js:7:[10](https://github.com/andreaswilli/meta-grabber/runs/5168925566?check_suite_focus=true#step:5:10)3)
      at _next (tests/app.test.js:9:194)
          at runMicrotasks (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        9.[13](https://github.com/andreaswilli/meta-grabber/runs/5168925566?check_suite_focus=true#step:5:13)8 s
Ran all test suites.
Error: Process completed with exit code 1.
```

**Comment by andreaswilli** [comment]
happened again on CI: https://github.com/andreaswilli/meta-grabber/actions/runs/3971789251/jobs/6809056138

**Comment by andreaswilli** [comment]
UI tests are disabled for the time being.
